name: Publish to GitHub Packages

on:
  push:
    branches: [ master ]  # ✅ Trigger when pushing to master branch

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # ✅ Needed to upload to GitHub Packages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github   # Must match <id> in pom.xml
          settings-path: ${{ github.workspace }}

      - name: Configure Maven with GitHub credentials
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings xmlns="http://maven.apache.org/SETTINGS/1.2.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.2.0 https://maven.apache.org/xsd/settings-1.2.0.xsd">
            <servers>
              <server>
                <id>github</id>
                <username>OKEAMAH</username>
                <password>${{ secrets.BASE_NODE_MAVEN_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Build and Publish to GitHub Packages
        run: mvn deploy --batch-mode
