name: Update Dockerfile Dependencies
on:
  # schedule:
  #   - cron: '0 12 * * * *'
  pull_request:

permissions:
  pull-requests: write
jobs:
  update:
    name: update
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Load .env file
        uses: xom9ikk/dotenv@v2.3.0
        with:
          path: ~/node/git_commit_message.env
          load-mode: strict
      - name: view env
        run: echo ${{ env.TITLE }}
      # - name: build dependency updater
      #   run: go build ./dependency_updater
      # - name: build dependency updater
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: ./dependency_updater --repo ~/node --commit true
      # - name: create pull request
      #   uses: peter-evans/create-pull-request@v7
      #   with:
      #     title: ${{ env.TITLE }}
      #     commit-message: ${{ env.TITLE }}
      #     body: ${{ env.DESC }}
      #     branch: update-dependencies