name: Update Dockerfile Dependencies
on:
  # schedule:
  #   - cron: '0 * * * *'
  pull_requests:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    name: update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: main

      - name: build dependency updater
        run: cd dependency_updater && go build

      - name: run dependency updater
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cd dependency_updater && ./dependency_updater --repo ../ --github-action true

      - name: Load .env file
        uses: aarcangeli/load-dotenv@2afd907c7bb1c0324d22a6192693213867e77443
        with:
          filenames: 'commit_message.env'

      - name: view env
        run: echo ${{ env.TITLE }}

      - name: create pull request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e
        with:
          title: ${{ env.TITLE }}
          commit-message: ${{ env.TITLE }}
          body: ${{ env.DESC }}
          branch: run-dependency-updater
          delete-branch: true